[package]
name = "rust-mysql-plugin"
version = "0.1.0"
authors = ["Matthew Miller <matthew.miller@appian.com>"]
edition = "2018"

[lib]
crate-type =["staticlib", "cdylib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

